app:
    resource: "@AppBundle/Controller/"
    type:     annotation

pages_index:
    path:     /
    defaults:  { _controller: AppBundle:Page:index }


user_registration_register:
    path:     /register/
    defaults: { _controller: AppBundle:Registration:register }

user_registration_confirm:
    path:     /register/confirm/{token}
    defaults: { _controller: AppBundle:Registration:confirm }

user_registration_confirmed:
    path:     /register/confirmed
    defaults: { _controller: AppBundle:Registration:confirmed }

user_resetting_request:
    path:     /resetting/request
    defaults: { _controller: AppBundle:Resetting:request }

user_resetting_send_email:
    path:     /resetting/send-email
    defaults: { _controller: AppBundle:Resetting:sendEmail }

user_resetting_reset:
    path:     /resetting/reset/{token}
    defaults: { _controller: AppBundle:Resetting:reset }

user_profile_show:
    path:     /profile
    defaults: { _controller: AppBundle:Profile:show }

user_profile_edit:
    path:     /profile/edit
    defaults: { _controller: AppBundle:Profile:edit }

user_profile_change_password:
    path:     /profile/change-password
    defaults: { _controller: AppBundle:ChangePassword:changePassword }

user_profile_first_login:
    path:     /profile/first-login
    defaults: { _controller: AppBundle:FirstLogin:firstLogin }

players_show:
    path:     /players/
    defaults: { _controller: AppBundle:Players:show }

players_post:
    path:     /post/{id}
    defaults: { _controller: AppBundle:Post:show }

players_create_post:
    path:     /post/create
    defaults: { _controller: AppBundle:Post:create }
