security:
    providers:
        database:
            entity:
                class: AppBundle:User

    encoders:
            AppBundle\Entity\User:
                algorithm: bcrypt

    firewalls:
        secured_area:
            pattern:    ^/
            provider: database
            anonymous: ~
            http_basic: ~
            form_login:
                login_path:  /login
                #check_path:  /login_check
                #success_handler: authentication_handler
                check_path:      /login_check
                success_handler: security.authentication_handler
                failure_handler: security.authentication_handler
                require_previous_session: false
            logout:
                path:   /logout
                target: /

