# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    steam.api_key: "152578BD7C0CDC7F213C8F9001C2FBF3"
    steam.format: "json"
    steam.app_id: "730"

services:
    app.mailer:
        class: AppBundle\Mailer\Mailer
        arguments: ["@service_container"]

    security.authentication_handler:
        class: AppBundle\Handler\AuthenticationHandler
        public: false
        arguments:
            - @router
            - @session
        calls:
            - [ setContainer, [@service_container ] ]

    app.steam:
        class:  AppBundle\Helper\SteamHelper
        arguments:
            - [%id]
        calls:
            - [ setContainer, [ @service_container ] ]

    form.errorMessages:
        class: AppBundle\Helper\FormErrorMessages
