<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function findPlayers($minimumRank, $maximumRank, $type, $id)
    {
        $qb = $em->createQueryBuilder();
        $qb->select('user')
            ->from('AppBundle:User', 'user')
            ->join('user.profile', 'profile')
            ->join('user.post', 'post')
            ->where($qb->expr()->between(
                'profile.rank',
                ':min',
                ':max'
            ))
            ->andWhere('post.type = :type')
            ->andWhere('user.id != :id')
            ->setParameters(array('min' => $minimumRank, 'max' => $maximumRank, 'type' => $type,'id' => $id));

        $query = $qb->getQuery();
        return $query->getResult();
    }
}
